exclude: |
  (?x)^(
    modules/aisearch/README.md|
    modules/aiservice/README.md|
    modules/aistudiohub/README.md|
    modules/aistudioproject/README.md|
    modules/applicationinsights/README.md|
    modules/containerregistry/README.md|
    modules/keyvault/README.md|
    modules/loganalytics/README.md|
    modules/storage/README.md|
    modules/userassignedidentity/README.md
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: ["--indent", "2", "--autofix", "--no-sort-keys"]
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.17.0
  hooks:
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/aisearch"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/aiservice"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/aistudiohub"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/aistudioproject"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/applicationinsights"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/containerregistry"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/keyvault"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/loganalytics"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/storage"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./modules/userassignedidentity"]
- repo: local
  hooks:
    - id: terraform-fmt
      name: terraform fmt
      description: runs terraform fmt
      entry: terraform fmt -recursive
      language: system
      pass_filenames: false
