name: keyvault tests
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "modules/keyvault/**"
      - ".ado/workflows/terraform-keyvault.yml"
pr:
  branches:
    include:
      - main
  paths:
    include:
      - "modules/keyvault/**"
      - ".ado/workflows/terraform-keyvault.yml"

variables:
  - template: templates/_defaultVariables.yml
  - template: templates/_defaultVariablesDev.yml

jobs:
  - template: templates/_terraformTestTemplate.yml
    parameters:
      environment: ${{ variables.environment_dev }}
      runner_name: ${{ variables.runner_name_dev }}
      config: "keyvault"
      terraform_version: ${{ variables.terraform_version }}
      node_version: ${{ variables.node_version }}
      service_connection_name: "mabuss1"
      run_test: true
      log_level_test: "ERROR"
