parameters:
- name: environment
  displayName: Environment
  type: string
- name: runner_name
  displayName: Runner Name
  type: string
- name: config
  displayName: Configuration
  type: string
- name: terraform_version
  displayName: Terraform Version
  type: string
- name: node_version
  displayName: Node Version
  type: string
- name: service_connection_name
  displayName: Service Connection Name
  type: string
- name: run_test
  displayName: Run Test
  type: boolean
- name: log_level_test
  displayName: Test Log Level
  type: string
  values:
    - "TRACE"
    - "DEBUG"
    - "INFO"
    - "WARN"
    - "ERROR"

jobs:
- job: lint
  displayName: Lint & Test
  continueOnError: false
  workspace:
    clean: all
  pool:
    name: ${{ parameters.runner_name }}

  steps:
    # Setup Terraform
    - task: TerraformInstaller@1
      displayName: Setup Terraform
      name: terraform_setup
      inputs:
        terraformVersion: ${{ parameters.terraform_version }}

    # Checkout repository
    - checkout: self
      displayName: Checkout repository
      name: checkout_repository
      submodules: true
      lfs: false
      clean: true
      continueOnError: false
      enabled: true

    # Terraform Format
    - bash: |
        terraform fmt -check -recursive
      displayName: Terraform Format
      name: terraform_format
      workingDirectory: "./modules/${{ parameters.config }}"

- job: test
  displayName: Terraform Test
  continueOnError: false
  condition: ${{ parameters.run_test }}
  workspace:
    clean: all
  pool:
    name: ${{ parameters.runner_name }}

  steps:
    # Setup Terraform
    - task: TerraformInstaller@1
      displayName: Setup Terraform
      name: terraform_setup
      inputs:
        terraformVersion: ${{ parameters.terraform_version }}

    # Checkout repository
    - checkout: self
      displayName: Checkout repository
      name: checkout_repository
      submodules: true
      lfs: false
      clean: true
      continueOnError: false
      enabled: true

    # Terraform Override
    - bash: |
        mv code/utilities/terraform_override.tf modules/$CONFIG
      displayName: Terraform Override
      name: terraform_override
      env:
        CONFIG: ${{ parameters.config }}

    # Azure login
    - task: AzureCLI@2
      displayName: Azure login
      name: azure_login
      inputs:
        # connectionType: "Azure Resource Manager" # Only supported in v3
        connectedServiceNameARM: ${{ parameters.service_connection_name }}
        scriptType: "bash"
        scriptLocation: "inlineScript"
        addSpnToEnvironment: false
        useGlobalConfig: true
        keepAzSessionActive: true
        visibleAzLogin: true
        inlineScript: |
          echo "Azure Login Succeeded"

    # Test
    - bash: |
        az account show
      displayName: Test
      name: az_test
      workingDirectory: "./modules/${{ parameters.config }}"
      env:
        TF_LOG: ${{ parameters.log_level_test }}

    # Terraform Init
    - bash: |
        terraform init
      displayName: Terraform Init
      name: terraform_init
      workingDirectory: "./modules/${{ parameters.config }}"

    # Terraform Test
    - bash: |
        terraform test
      displayName: Terraform Test
      name: terraform_test
      workingDirectory: "./modules/${{ parameters.config }}"
      env:
        TF_LOG: ${{ parameters.log_level_test }}
