name: Function App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "code/function/**"
      - "tests/**"
      - "requirements.txt"

  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "code/function/**"
      - "tests/**"
      - "requirements.txt"

jobs:
  function_test:
    uses: ./.github/workflows/_functionAppTestTemplate.yml
    name: "Function App Test"
    with:
      python_version: "3.11"
      function_directory: "./code/function"

  function_container:
    uses: ./.github/workflows/_containerTemplate.yml
    name: "Function App Container"
    needs: [function_test]
    with:
      environment: "dev"
      working_directory: "./code/function"
      registry_uri: "ghcr.io"
      image_namespace_name: "PerfectThymeTech"
      image_name: "AzureFunctionPython"
    secrets:
      USER_NAME: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  # function_deploy:
  #   uses: ./.github/workflows/_functionAppDeployTemplate.yml
  #   name: "Function App Deploy"
  #   needs: [function_test]
  #   if: github.event_name == 'push' || github.event_name == 'release'
  #   with:
  #     environment: "dev"
  #     python_version: "3.10"
  #     function_directory: "./code/function"
  #     function_name: "myfunc-dev-fctn001"
  #     tenant_id: "3556be79-2979-4b19-a1af-4dd4e6d9ed7e"
  #     subscription_id: "8f171ff9-2b5b-4f0f-aed5-7fa360a1d094"
  #   secrets:
  #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
  #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
