name: Infrastructure Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - "config/**"
      - ".github/workflows/terraform.yml"
      - ".github/workflows/_terraformEnvironmentTemplate.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - "config/**"
      - ".github/workflows/terraform.yml"
      - ".github/workflows/_terraformEnvironmentTemplate.yml"

jobs:
  terraform_dev:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Dev"
    with:
      environment: "dev"
      config: "PerfectThymeTech"
      terraform_version: "1.6.6"
      node_version: 18
      working_directory: "./code/infra"
      tenant_id: "3556be79-2979-4b19-a1af-4dd4e6d9ed7e"
      subscription_id: "8f171ff9-2b5b-4f0f-aed5-7fa360a1d094"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      MY_SAMPLE_SECRET: ${{ secrets.MY_SAMPLE_SECRET }}
